version: '3.3'

services:
  consignment:
    build: ./services/consignment
    image: consignment-service:latest
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://mongo:27017"
      WAIT_HOSTS: mongo:27017
    links:
      - mongo
    depends_on:
      - mongo

  vessel:
    build: ./services/vessel
    image: vessel-service:latest
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://mongo:27017"
      WAIT_HOSTS: mongo:27017
    links:
      - mongo
    depends_on:
      - mongo

  user:
    build: ./services/user
    image: user-service:latest
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      WAIT_HOSTS: postgres:5432
    links:
      - postgres
    depends_on:
      - postgres

  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./data:/data/db

  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  mongo_data:
