version: '3.3'

services:
  web:
    image: micro/micro
    depends_on:
      - consignment
      - vessel
      - user
    command: "web"
    ports:
      - 8082:8082
    environment:
      MICRO_REGISTRY: "mdns"

  api:
    image: micro/micro:v2.0.0 # Version must match the go-micro version in the services to work https://github.com/micro/go-micro/issues/1141
    command: "api"
    ports:
      - 8080:8080
    environment:
      MICRO_ADDRESS: ":8080"
      MICRO_REGISTRY: "mdns"
      MICRO_API_NAMESPACE: "com.foo.service"
      MICRO_API_HANDLER: "rpc"
      MICRO_API_ENABLE_RPC: "true"

  consignment:
    build: ./services/consignment
    image: consignment-service:latest
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://mongo:27017"
      WAIT_HOSTS: mongo:27017
    links:
      - mongo
    depends_on:
      - mongo

  vessel:
    build: ./services/vessel
    image: vessel-service:latest
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://mongo:27017"
      WAIT_HOSTS: mongo:27017
    links:
      - mongo
    depends_on:
      - mongo

  user:
    build: ./services/user
    image: user-service:latest
    ports:
      - 50053:50051
    environment:
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats://nats:4222"
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      WAIT_HOSTS: postgres:5432
    links:
      - postgres
      - nats
    depends_on:
      - postgres
      - nats

  email:
    build: ./services/email
    image: email-service:latest
    environment:
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats://nats:4222"
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      WAIT_HOSTS: nats:4222
    links:
      - nats
    depends_on:
      - nats

  user-api:
    build: ./services/user-api
    image: user-api:latest
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./data:/data/db

  postgres:
    image: postgres
    expose:
      - "5432"
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nats:
    image: nats
    expose:
      - 4222

volumes:
  mongo_data:
