version: '3.1'

services:
  user:
    build: services/user
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./user_service'
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  datastore:
    image: mongo
    expose:
      - "27017"

  database:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
