apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
        containers:
        - name: micro
          image: micro/micro
          args:
            - "api"
          env:
          - name: MICRO_API_ADDRESS
            value: ":80"
          - name: MICRO_REGISTRY
            value: "mdns"
          - name: MICRO_API_NAMESPACE
            value: "com.foo.service"
          - name: MICRO_API_HANDLER
            value: "rpc"
          - name: MICRO_API_ENABLE_RPC
            value: "true"
          ports:
          - containerPort: 80
            name: port
