apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: default
    name: shippy-ui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shippy-ui
    template:
        metadata:
            labels:
                app: shippy-ui
        spec:
            containers:
                - name: shippy-ui
                  image: shippy-ui:latest
                  imagePullPolicy: Never
                  env:
                      - name: UPDATED_AT
                        value: "Mon 15 Jun 2020 10:18:24 AM BST"
                  ports:
                      - containerPort: 80
                        name: shippy-ui-port
