apiVersion: v1
kind: Service
metadata:
    name: shippy-ui
    labels:
        app: shippy-ui
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: "shippy-ui-port"
    selector:
        app: "shippy-ui"
