apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: default
    name: consignment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: consignment
    template:
        metadata:
            labels:
                app: consignment
        spec:
            containers:
                - name: consignment-service
                  image: consignment-service:latest
                  imagePullPolicy: Never
                  command: [
                      "./consignment-service",
                      "--selector=static",
                      "--server_address=:8080",
                  ]
                  env:
                      - name: DB_HOST
                        value: "mongodb://mongo:27017"
                      - name: UPDATED_AT
                        value: "Sat 13 Jun 2020 09:50:24 AM BST"
                  ports:
                      - containerPort: 8080
                        name: cons-port
