apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: default
    name: user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - name: user-service
                  image: user-service:latest
                  imagePullPolicy: Never
                  command: [
                      "./user-service",
                      "--selector=static",
                      "--server_address=:8080",
                  ]
                  env:
                      - name: MICRO_REGISTRY
                        value: mdns
                      - name: MICRO_ADDRESS
                        value: :50051
                      - name: DB_HOST
                        value: "postgres"
                      - name: DB_PORT
                        value: "5432"
                      - name: DB_NAME
                        value: "postgres"
                      - name: DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: postgres
                            key: password
                      - name: DB_USER
                        value: "postgres"
                      - name: UPDATED_AT
                        value: "Mon 15 Jun 2020 10:06:28 AM BST"
                  ports:
                      - containerPort: 8080
                        name: user-port
